/*import dynamic from 'next/dynamic'; 
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHome, faChartLine, faProjectDiagram, faUserFriends, faClipboardList, faSignOutAlt } from "@fortawesome/free-solid-svg-icons";
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react'; // Importez ReactNode
import ProjetPage from "./page";
import TableauDeBordPage from "./tableau-de-bord/page";
import MembrePage from "./membre/page";
import RapportPage from "./rapport/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; // Utilisez ReactNode pour typage children
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div id="menu">
            <button className="menu-button">
              <a className="menu-button" href="/">
                <FontAwesomeIcon icon={faHome} className="menu-icon" />
                Accueil
              </a>
            </button>
            <button className="menu-button">
              <a className="menu-button" href="/espaceAdmin/tableau-de-bord">
                <FontAwesomeIcon icon={faChartLine} className="menu-icon" />
                Tableau de bord
              </a>
            </button>
            <button className="menu-button">
              <a className="menu-button" href="/espaceAdmin/projet">
                <FontAwesomeIcon icon={faProjectDiagram} className="menu-icon" />
                Projet
              </a>
            </button>
            <button className="menu-button">
              <a className="menu-button" href="/espaceAdmin/membre">
                <FontAwesomeIcon icon={faUserFriends} className="menu-icon" />
                Membre
              </a>
            </button>
            <button className="menu-button">
              <a className="menu-button" href="/espaceAdmin/rapport">
                <FontAwesomeIcon icon={faClipboardList} className="menu-icon" />
                Rapport et analyse
              </a>
            </button>
            <div className="menu-button" >
              <a className="menu-button" href="/">
                <FontAwesomeIcon icon={faSignOutAlt} className="menu-icon" />
                Déconnexion
              </a>
            </div>
          </div>

          <div id="resultat">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
*/

/*
import dynamic from 'next/dynamic'; 
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHome, faChartLine, faProjectDiagram, faUserFriends, faClipboardList, faSignOutAlt } from "@fortawesome/free-solid-svg-icons";
import { useRouter } from 'next/router';
import React, { ReactNode } from 'react'; // Importez ReactNode
import ProjetPage from "./page";
import TableauDeBordPage from "./tableau-de-bord/page";
import MembrePage from "./membre/page";
import RapportPage from "./rapport/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; // Utilisez ReactNode pour typage children
}



export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <div>
          <div id="menu">
            <button>
              <a href="/">
                <FontAwesomeIcon icon={faHome} className="menu-icon" />
                Accueil
              </a>
            </button>
            <button>
              <a className="menu-button" href="/espaceAdmin/tableau-de-bord">
                <FontAwesomeIcon icon={faChartLine} className="menu-icon" />
                Tableau de bord
              </a>
            </button>
            <button>
              <a href="/espaceAdmin/projet">
                <FontAwesomeIcon icon={faProjectDiagram} className="menu-icon" />
                Projet
              </a>
            </button>
            <button>
              <a className="menu-button" href="/espaceAdmin/membre">
                <FontAwesomeIcon icon={faUserFriends} className="menu-icon" />
                Membre
              </a>
            </button>
            <button>
              <a href="/espaceAdmin/rapport">
                <FontAwesomeIcon icon={faClipboardList} className="menu-icon" />
                Rapport et analyse
              </a>
            </button>
            <div>
              <a href="/">
                <FontAwesomeIcon icon={faSignOutAlt} className="menu-icon" />
                Déconnexion
              </a>
            </div>

            
          </div>

          <div id="resultat">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}
*/

"use client"
import dynamic from 'next/dynamic'; 
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHome, faChartLine, faProjectDiagram, faUserFriends, faClipboardList, faSignOutAlt, faSun, faMoon } from "@fortawesome/free-solid-svg-icons";
import React, { useState, ReactNode } from 'react'; // Importez ReactNode
import ProjetPage from "./page";
import TableauDeBordPage from "./tableau-de-bord/page";
import MembrePage from "./membre/page";
import RapportPage from "./rapport/page";
import Layout from './Layout';
const inter = Inter({ subsets: ["latin"] });


interface RootLayoutProps {
  children: ReactNode; // Utilisez ReactNode pour typage children
}

export default function RootLayout({ children }: RootLayoutProps) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
  };

  return (
    <html lang="en" className={isDarkMode ? 'dark' : 'light'}>
      <body className={`${inter.className} ${isDarkMode ? 'dark' : 'light'}`}>
        
        <div>
          <div id="menu">
            {/*<button>
  <a onClick={toggleDarkMode} className="toggle-theme-button" title="Toggle theme">
    <FontAwesomeIcon icon={isDarkMode ? faSun : faMoon} className="menu-icon" />
    <span className="sr-only">Toggle theme</span>
  </a>
  </button>*/}

            <button>
              <a className="menu-button" href="/espaceAdmin/tableau-de-bord">
                <FontAwesomeIcon icon={faChartLine} className="menu-icon" />
                <span className="text-black">Tableau de bord</span>
              </a>
            </button>
            <button>
              <a href="/espaceAdmin/projet">
                <FontAwesomeIcon icon={faProjectDiagram} className="menu-icon" />
                <span className="text-black">Projet</span>
              </a>
            </button>
            <button>
              <a className="menu-button" href="/espaceAdmin/membre">
                <FontAwesomeIcon icon={faUserFriends} className="menu-icon" />
                <span className="text-black">Membre</span>
              </a>
            </button>
            <button>
              <a href="/espaceAdmin/rapport">
                <FontAwesomeIcon icon={faClipboardList} className="menu-icon" />
                <span className="text-black">Rapport et analyse</span>
              </a>
            </button>
            <div>
              <a href="/">
                <FontAwesomeIcon icon={faSignOutAlt} className="menu-icon" />
                <span className="text-black">Déconnexion</span>
              </a>
            </div>
          </div>
          
          <div id="resultat" className="flex items-center justify-center h-screen" >
          </div>
            {children}
          </div><Layout>
            <div className="flex flex-col items-center justify-center h-screen w-auto ">
              <div className="flex items-center justify-center w-full">
                <div className="flex flex-col justify-center items-start p-8">
                  <h1 className="text-6xl font-bold text-blue-500 animate-title">Bienvenue chez votre espace admin</h1>
                  <p className="mt-4 text-lg">
                    Bienvenue dans votre espace d'administration.
                    Ici, vous pouvez gérer vos projets et suivre leur avancement.
                    Utilisez le menu pour naviguer entre les différentes sections.
                  </p>
                  <a href="/espaceAdmin/objectifs" className="mt-6 bg-green-500 text-white px-4 py-2 ounded animate-button rounded-lg">
                    Projet En Cours ⇢
                  </a>
                </div>
                <div className="">
                  <img src="/Admin1-removebg-preview.png" alt="Espace Admin" width="auto" height="auto"/>
                </div>
              </div>
             </div>
             <style jsx>{`
  @keyframes pulse {
    0%, 100% {
      transform: scale(1);
    }
    50% {
      transform: scale(1.1);
    }
  }
  @keyframes fadeIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }
  .animate-button {
    animation: pulse 7s infinite;
  }
  .animate-title {
    animation: fadeIn 3s ease-in-out;
  }
`}</style>
        </Layout>
      </body>
    </html>
  );
}
